package client

import (
	"context"
	"fmt"
	"math"
	"sort"
	"strings"
	"time"
)

// Object434 preserves transmitted fields, including indices not yet named.
// Missing fields are unknown, not silently reported as zero.
type Object434 struct {
	GUID      uint64
	Type      uint8
	Created   bool
	ThisIsYou bool
	Map       uint16
	Position  *Position434
	Movement  *Movement434
	Fields    map[uint16]uint32
	Revision  uint64
}

// ObjectStore434 is owned by one session loop. Objects returns GUID-sorted
// snapshots; no caller can mutate the store through an exposed map.
type ObjectStore434 struct {
	PlayerGUID uint64
	Map        uint16
	HasMap     bool
	objects    map[uint64]*Object434
	revision   uint64
}

func (s *ObjectStore434) Objects() []Object434 {
	result := make([]Object434, 0, len(s.objects))
	for _, o := range s.objects {
		copyObject := *o
		copyObject.Fields = make(map[uint16]uint32, len(o.Fields))
		for k, v := range o.Fields {
			copyObject.Fields[k] = v
		}
		if o.Position != nil {
			p := *o.Position
			copyObject.Position = &p
		}
		if o.Movement != nil {
			m := o.Movement.clone()
			copyObject.Movement = &m
		}
		result = append(result, copyObject)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].GUID < result[j].GUID })
	return result
}
func (s *ObjectStore434) setMap(m uint16) {
	if !s.HasMap || s.Map != m {
		s.objects = make(map[uint64]*Object434)
		s.Map = m
		s.HasMap = true
	}
}
func (s *ObjectStore434) ApplyUpdate(b []byte) error {
	m, ds, err := parseObjectUpdate434(b)
	if err != nil {
		return err
	}
	// Validate identity before applying any part of the packet.
	for _, d := range ds {
		if d.self && (d.guid != s.PlayerGUID || d.typeID != 4) {
			return fmt.Errorf("ThisIsYou does not match enumerated player")
		}
	}
	s.setMap(m)
	for _, d := range ds {
		s.revision++
		if d.kind == 3 {
			for _, g := range d.removed {
				delete(s.objects, g)
			}
			continue
		}
		o := s.objects[d.guid]
		if o == nil || d.kind != 0 {
			o = &Object434{GUID: d.guid, Map: m, Fields: make(map[uint16]uint32)}
			s.objects[d.guid] = o
		}
		if d.kind != 0 {
			o.Type = d.typeID
			o.Created = true
			o.ThisIsYou = d.self
			o.Position = d.position
			o.Movement = d.movement
		}
		for k, v := range d.fields {
			o.Fields[k] = v
		}
		o.Revision = s.revision
	}
	return nil
}
func (s *ObjectStore434) ApplyDestroy(b []byte) error {
	r := newObjectReader434(b)
	g := r.u64()
	dead := r.u8()
	if err := r.done(); err != nil {
		return err
	}
	if dead > 1 {
		return fmt.Errorf("invalid destroy death flag")
	}
	delete(s.objects, g)
	s.revision++
	return nil
}

// Field indices from TCPP's autogenerated build-15595 UpdateFields.h.
const (
	FieldUnitBytes434 uint16 = 0x19
	FieldHealth434    uint16 = 0x1a
	FieldPower1434    uint16 = 0x1b
	FieldMaxHealth434 uint16 = 0x20
	FieldMaxPower1434 uint16 = 0x21
	FieldLevel434     uint16 = 0x30
	FieldFaction434   uint16 = 0x31
	FieldDisplay434   uint16 = 0x3d
)

// PrimaryPowerSlot434 follows DBCManager's row-order assignment using the
// build-15595 ChrClassesXPowerTypes.dbc. Unknown class/type pairs stay unknown.
func PrimaryPowerSlot434(class, power uint8) (uint16, bool) {
	rows := map[uint8][]uint8{1: {1, 10}, 2: {0, 9, 10}, 3: {2, 10}, 4: {3, 10}, 5: {0, 10}, 6: {6, 10}, 7: {0, 10}, 8: {0, 10}, 9: {0, 7, 10}, 11: {0, 1, 3, 8, 10}}
	for i, p := range rows[class] {
		if p == power {
			return uint16(i), true
		}
	}
	return 0, false
}

type WorldState434Result struct {
	Login          CharacterLogin434Result
	Store          ObjectStore434
	Opcodes        map[uint16]int
	WorldVariables map[uint32]int32
	Area, Subarea  int32
	Warnings       []string
}

func (s *WorldState434Result) observe(p loginPacket434) error {
	s.Opcodes[p.op]++
	switch p.op {
	case cataUpdateObject:
		return s.Store.ApplyUpdate(p.body)
	case cataDestroyObject:
		return s.Store.ApplyDestroy(p.body)
	case cataMoveUpdate:
		return s.Store.ApplyMovement(p.body)
	case cataInitWorldStates:
		r := newObjectReader434(p.body)
		m := r.u32()
		a, sa := int32(r.u32()), int32(r.u32())
		n := int(r.u16())
		if m > 65535 || !r.bounded(n, 8) {
			return fmt.Errorf("invalid INIT_WORLD_STATES map/count")
		}
		vars := make(map[uint32]int32, n)
		for i := 0; i < n; i++ {
			k := r.u32()
			vars[k] = int32(r.u32())
		}
		if err := r.done(); err != nil {
			return err
		}
		s.Store.setMap(uint16(m))
		s.Area = a
		s.Subarea = sa
		s.WorldVariables = vars
	case cataUpdateWorldState:
		r := newObjectReader434(p.body)
		k := r.u32()
		v := int32(r.u32())
		hidden := r.u8()
		if err := r.done(); err != nil {
			return err
		}
		if hidden > 1 {
			return fmt.Errorf("invalid world-state hidden flag")
		}
		s.WorldVariables[k] = v
	case cataNewWorld:
		// Cross-map transfer needs acknowledgments outside this stationary probe.
		// Decode framing and invalidate stale objects, then fail explicitly.
		r := newObjectReader434(p.body)
		pos := Position434{X: r.f32(), Orientation: r.f32(), Z: r.f32()}
		m := r.u32()
		pos.Y = r.f32()
		if err := r.done(); err != nil {
			return err
		}
		if m > 65535 || !finitePosition434(&pos) {
			return fmt.Errorf("invalid NEW_WORLD")
		}
		s.Store.setMap(uint16(m))
		return fmt.Errorf("world transition requires a later transfer milestone")
	}
	return nil
}
func (s *WorldState434Result) playerReady() (bool, error) {
	p := s.Store.objects[s.Store.PlayerGUID]
	if p == nil || !p.Created || p.Position == nil {
		return false, nil
	}
	if p.Type != 4 {
		return false, fmt.Errorf("enumerated player created as type %d", p.Type)
	}
	if int32(p.Map) != s.Login.Map {
		return false, fmt.Errorf("object map differs from LOGIN_VERIFY_WORLD")
	}
	pos := p.Position
	for _, d := range []float32{pos.X - s.Login.X, pos.Y - s.Login.Y, pos.Z - s.Login.Z} {
		if math.Abs(float64(d)) > 0.1 {
			return false, fmt.Errorf("player position differs from LOGIN_VERIFY_WORLD")
		}
	}
	angle := math.Remainder(float64(pos.Orientation-s.Login.Orientation), 2*math.Pi)
	if math.Abs(angle) > 0.01 {
		return false, fmt.Errorf("player orientation differs from LOGIN_VERIFY_WORLD")
	}
	if lo, ok := p.Fields[0]; ok && lo != uint32(p.GUID) {
		return false, fmt.Errorf("player GUID field mismatch")
	}
	if hi, ok := p.Fields[1]; ok && hi != uint32(p.GUID>>32) {
		return false, fmt.Errorf("player GUID field mismatch")
	}
	return true, nil
}

// ObserveWorld434 performs a bounded stationary observation. The only outgoing
// post-selection packets are the existing login, instance auth and time sync.
func ObserveWorld434(ctx context.Context, username string, key []byte, realm RealmInfo, name, expectedInstance string) (WorldState434Result, error) {
	s := WorldState434Result{Opcodes: make(map[uint16]int), WorldVariables: make(map[uint32]int32)}
	if name == "" || expectedInstance == "" {
		return s, fmt.Errorf("character name and expected instance address are required")
	}
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	err := withWorld434(ctx, username, key, realm, func(w *worldWire434) error {
		roster, err := enumerateOnWorld434(w)
		if err != nil {
			return err
		}
		c, err := selectLoginCharacter434(roster, name)
		if err != nil {
			return err
		}
		s.Login.Character = c
		s.Store.PlayerGUID = c.GUID
		if err := w.send(cataPlayerLogin, loginGUID434(c.GUID)); err != nil {
			return err
		}
		var readyAt time.Time
		complete := func() (bool, error) {
			ready, err := s.playerReady()
			if err != nil {
				return false, err
			}
			if !ready {
				readyAt = time.Time{}
				return false, nil
			}
			if readyAt.IsZero() {
				readyAt = time.Now()
			}
			return time.Since(readyAt) >= time.Second, nil
		}
		return awaitObservedLogin434(ctx, w, strings.ToUpper(username), expectedInstance, &s.Login, openInstance434, s.observe, complete)
	})
	return s, err
}
